In [1]:
import pandas as pd
import numpy as np

In [2]:
df_ad_t = pd.read_csv('ad_title.csv')

In [3]:
df_ad_t.head()

adId  wordId
0     6      24
1     6      25
2     6      26
3     6      27
4     6      28

In [4]:
df_ad_t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18122 entries, 0 to 18121
Data columns (total 2 columns):
adId      18122 non-null int64
wordId    18122 non-null int64
dtypes: int64(2)
memory usage: 283.3 KB


In [5]:
arr = pd.DataFrame(df_ad_t['wordId'])
arr = arr.drop_duplicates().reset_index()
print(arr)

      index  wordId
0         0      24
1         1      25
2         2      26
3         3      27
4         4      28
...     ...     ...
2103  18051    2681
2104  18058    2682
2105  18084    1965
2106  18094    2683
2107  18101    1861

[2108 rows x 2 columns]


In [6]:
df_adtitleg = df_ad_t.groupby(['wordId','adId']).agg({'adId':['count']}).reset_index()

In [7]:
df_adtitleg.tail(10)

wordId  adId      
                   count
18112   2677  7827     1
18113   2678  7828     1
18114   2679  7833     1
18115   2680  7851     1
18116   2680  7854     1
18117   2681  7853     1
18118   2681  7857     1
18119   2682  7854     1
18120   2683  7861     1
18121   2683  7867     1

In [8]:
df_adtitleg.max()

wordId           2683
adId             7867
        count       1
dtype: int64

In [9]:
df_adtitleg['adId'].max()

         7867
count       1
dtype: int64

In [10]:
df_adtitleg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18122 entries, 0 to 18121
Data columns (total 3 columns):
(wordId, )       18122 non-null int64
(adId, )         18122 non-null int64
(adId, count)    18122 non-null int64
dtypes: int64(3)
memory usage: 424.9 KB


In [11]:
arr['index'] = arr['wordId']
arr['wordId'] = arr['wordId'].astype('object')
print(arr)

      index wordId
0        24     24
1        25     25
2        26     26
3        27     27
4        28     28
...     ...    ...
2103   2681   2681
2104   2682   2682
2105   1965   1965
2106   2683   2683
2107   1861   1861

[2108 rows x 2 columns]


In [12]:
df_inx = pd.get_dummies(arr)
df_inx.sample(10)

index  wordId_0  wordId_1  wordId_3  wordId_4  wordId_5  wordId_6  \
662    1493         0         0         0         0         0         0   
324     722         0         0         0         0         0         0   
1472   1699         0         0         0         0         0         0   
162     335         0         0         0         0         0         0   
278     655         0         0         0         0         0         0   
1702   1704         0         0         0         0         0         0   
872    1464         0         0         0         0         0         0   
1599   1912         0         0         0         0         0         0   
282     662         0         0         0         0         0         0   
2080   2667         0         0         0         0         0         0   

      wordId_7  wordId_8  wordId_9  ...  wordId_2674  wordId_2675  \
662          0         0         0  ...            0            0   
324          0         0         0  ...            0            0   
1472         0         0         0  ...            0            0   
162          0         0         0  ...            0            0   
278          0         0         0  ...            0            0   
1702         0         0         0  ...            0            0   
872          0         0         0  ...            0            0   
1599         0         0         0  ...            0            0   
282          0         0         0  ...            0            0   
2080         0         0         0  ...            0            0   

      wordId_2676  wordId_2677  wordId_2678  wordId_2679  wordId_2680  \
662             0            0            0            0            0   
324             0            0            0            0            0   
1472            0            0            0            0            0   
162             0            0            0            0            0   
278             0            0            0            0            0   
1702            0            0            0            0            0   
872             0            0            0            0            0   
1599            0            0            0            0            0   
282             0            0            0            0            0   
2080            0            0            0            0            0   

      wordId_2681  wordId_2682  wordId_2683  
662             0            0            0  
324             0            0            0  
1472            0            0            0  
162             0            0            0  
278             0            0            0  
1702            0            0            0  
872             0            0            0  
1599            0            0            0  
282             0            0            0  
2080            0            0            0  

[10 rows x 2109 columns]

In [13]:
result = []
for i, row in df_inx.iterrows():
    result.append(row.iloc[1:])
df_r = pd.DataFrame(result)
df_r.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2108 entries, 0 to 2107
Columns: 2108 entries, wordId_0 to wordId_2683
dtypes: int64(2108)
memory usage: 33.9 MB


In [14]:
matr = df_r.to_numpy()
print(matr)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]


In [15]:
del(df_r)

In [16]:
result = []
for i in range(0,len(matr)):
    result += [[df_inx['index'].iloc[i],matr[i,:]]]
df_r = pd.DataFrame(result)
df_r.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2108 entries, 0 to 2107
Data columns (total 2 columns):
0    2108 non-null int64
1    2108 non-null object
dtypes: int64(1), object(1)
memory usage: 33.1+ KB


In [19]:
df_r.rename(columns={0:'index'}, inplace = True)
df_r.head(10)

index                                                  1
0     24  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1     25  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2     26  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3     27  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4     28  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
5     29  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
6     30  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
7     31  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
8     32  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
9     33  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

In [18]:
del(df_inx)